import fs from 'fs';
import path from 'path';
import os from 'os';
import { v4 as uuidv4 } from 'uuid';

export interface ServerDefaults {
  port: number;
  maxPlayers: number;
  gamemode: 'survival' | 'creative' | 'adventure' | 'spectator';
  difficulty: 'peaceful' | 'easy' | 'normal' | 'hard';
  onlineMode: boolean;
  allowFlight: boolean;
  viewDistance: number;
  simDistance: number;
  motd: string;
  seed?: string;
  levelName: string;
}

const DEFAULT_PROPS: ServerDefaults = {
  port: 25565,
  maxPlayers: 20,
  gamemode: 'survival',
  difficulty: 'normal',
  onlineMode: true,
  allowFlight: false,
  viewDistance: 10,
  simDistance: 10,
  motd: 'A MineControl OS Server',
  levelName: 'world',
};

export function generateServerProperties(serverDir: string, overrides?: Partial<ServerDefaults>): string {
  const opts = { ...DEFAULT_PROPS, ...overrides };
  const seed = opts.seed || Math.floor(Math.random() * 2147483647).toString();
  const port = opts.port;
  const rconPort = port + 10;
  const queryPort = port + 1;

  const props = [
    '#Minecraft server properties',
    '#Generated by MineControl OS',
    `#${new Date().toISOString()}`,
    '',
    'allow-flight=' + opts.allowFlight,
    'allow-nether=true',
    'broadcast-console-to-ops=true',
    'broadcast-rcon-to-ops=true',
    'bug-report-link=',
    'difficulty=' + opts.difficulty,
    'enable-command-block=false',
    'enable-jmx-monitoring=false',
    'enable-query=false',
    'enable-rcon=false',
    'enable-status=true',
    'enforce-secure-profile=' + (opts.onlineMode ? 'true' : 'false'),
    'entity-broadcast-range-percentage=100',
    'force-gamemode=false',
    'function-permission-level=2',
    'gamemode=' + opts.gamemode,
    'generate-structures=true',
    'generator-settings={}',
    'hardcore=false',
    'hide-online-players=false',
    'initial-disabled-payloads=',
    'initial-enabled-payloads=',
    'level-name=' + opts.levelName,
    'level-seed=' + seed,
    'level-type=minecraft:normal',
    'max-chained-neighbor-updates=1000000',
    'max-players=' + opts.maxPlayers,
    'max-tick-time=60000',
    'max-world-size=29999984',
    'motd=' + opts.motd,
    'network-compression-threshold=256',
    'online-mode=' + opts.onlineMode,
    'op-permission-level=4',
    'player-idle-timeout=0',
    'previews-chat=false',
    'prevent-proxy-connections=false',
    'pvp=true',
    'query.port=' + queryPort,
    'rate-limit=0',
    'rcon.password=',
    'rcon.port=' + rconPort,
    'region-file-compression=deflate',
    'require-resource-pack=false',
    'resource-pack=',
    'resource-pack-id=',
    'resource-pack-prompt=',
    'resource-pack-sha1=',
    'server-id=' + uuidv4().replace(/-/g, ''),
    'server-ip=',
    'server-port=' + port,
    'simulation-distance=' + opts.simDistance,
    'spawn-animals=true',
    'spawn-monsters=true',
    'spawn-npcs=true',
    'spawn-protection=16',
    'sync-chunk-writes=true',
    'text-filtering-config=',
    'use-native-transport=true',
    'view-distance=' + opts.viewDistance,
    'white-list=false',
  ];

  const content = props.join('\n') + '\n';
  const propsPath = path.join(serverDir, 'server.properties');
  fs.writeFileSync(propsPath, content, 'utf-8');
  return seed;
}

export function acceptEula(serverDir: string): void {
  const eulaPath = path.join(serverDir, 'eula.txt');
  const content = [
    '#By changing the setting below to TRUE you are indicating your agreement to our EULA (https://aka.ms/MinecraftEULA).',
    '#',
    `#${new Date().toISOString()}`,
    'eula=true',
  ].join('\n') + '\n';
  fs.writeFileSync(eulaPath, content, 'utf-8');
}

export function createOpsJson(serverDir: string, ops?: Array<{ uuid: string; name: string; level: number }>): void {
  const opsPath = path.join(serverDir, 'ops.json');
  const data = ops || [
    { uuid: '', name: 'default', level: 4, bypassesPlayerLimit: true }
  ];
  fs.writeFileSync(opsPath, JSON.stringify(data, null, 2), 'utf-8');
}

export function createWhitelistJson(serverDir: string, whitelisted?: any[]): void {
  const wlPath = path.join(serverDir, 'whitelist.json');
  fs.writeFileSync(wlPath, JSON.stringify(whitelisted || [], null, 2), 'utf-8');
}

export function createBannedPlayersJson(serverDir: string): void {
  fs.writeFileSync(path.join(serverDir, 'banned-players.json'), '[]\n', 'utf-8');
}

export function createBannedIpsJson(serverDir: string): void {
  fs.writeFileSync(path.join(serverDir, 'banned-ips.json'), '[]\n', 'utf-8');
}

export function createServerDirectories(serverDir: string): string[] {
  const dirs = [
    path.join(serverDir, 'world'),
    path.join(serverDir, 'world', 'region'),
    path.join(serverDir, 'world', 'data'),
    path.join(serverDir, 'world', 'dimensions'),
    path.join(serverDir, 'backups'),
    path.join(serverDir, 'logs'),
    path.join(serverDir, 'plugins'),
    path.join(serverDir, 'mods'),
    path.join(serverDir, 'config'),
    path.join(serverDir, 'crash-reports'),
    path.join(serverDir, 'libraries'),
    path.join(serverDir, 'cache'),
  ];

  const created: string[] = [];
  for (const dir of dirs) {
    if (!fs.existsSync(dir)) {
      fs.mkdirSync(dir, { recursive: true });
      created.push(dir);
    }
  }
  return created;
}

export function configureServer(serverDir: string, overrides?: Partial<ServerDefaults>): { seed: string; dirs: string[] } {
  const dirs = createServerDirectories(serverDir);
  acceptEula(serverDir);
  createOpsJson(serverDir);
  createWhitelistJson(serverDir);
  createBannedPlayersJson(serverDir);
  createBannedIpsJson(serverDir);
  const seed = generateServerProperties(serverDir, overrides);
  return { seed, dirs };
}

export function getRecommendedJavaVersion(source: string, mcVersion: string): number {
  if (source === 'Velocity' || source === 'Waterfall' || source === 'BungeeCord')
    return 17;

  if (!mcVersion) return 21;
  const parts = mcVersion.split('.').map(n => parseInt(n, 10));
  if (parts.length < 2) return 21;
  const minor = parts[1];
  const patch = parts.length > 2 ? parts[2] : 0;

  if (minor <= 16) return 8;
  if (minor === 17) return 17;
  if (minor >= 18 && minor <= 20) {
    if (minor === 20 && patch >= 5) return 21;
    return 17;
  }
  return 21;
}
